# Generated by Django 5.0.6

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_is_verified(apps, schema_editor):
    """Copy is_verified=True to domain_verified=True + verification_status='verified'."""
    Company = apps.get_model("companies", "Company")
    Company.objects.filter(is_verified=True).update(
        domain_verified=True,
        verification_status="verified",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add all new fields
        migrations.AddField(
            model_name="company",
            name="domain",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="domain_verification_token",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="company",
            name="domain_verification_token_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="domain_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="company",
            name="registration_document",
            field=models.FileField(blank=True, null=True, upload_to="verification_docs/"),
        ),
        migrations.AddField(
            model_name="company",
            name="registration_number",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="company",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="company",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("unverified", "Unverified"),
                    ("pending", "Pending Review"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                ],
                default="unverified",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_companies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-200", "51-200"),
                    ("201-500", "201-500"),
                    ("501-1000", "501-1000"),
                    ("1000+", "1000+"),
                ],
                max_length=20,
            ),
        ),
        # Step 2: Migrate data from is_verified → new fields
        migrations.RunPython(migrate_is_verified, migrations.RunPython.noop),
        # Step 3: Remove old field
        migrations.RemoveField(
            model_name="company",
            name="is_verified",
        ),
    ]
